FROM opensuse/leap:15                                                                                                                                                                                                                                                             
RUN zypper --non-interactive install python3-pip  make  gcc zlib
RUN pip install CrossMap
