[build-system]
requires = [
  "setuptools",
]
build-backend = "setuptools.build_meta"

[project]
name = "ngs_pipeline"
version = "0.0.1"
dependencies = [
"flask",
"requests",
"pycouchdb",
"celery",
"pytest",
"pyparsing",
"click",
"pandas",
"pydantic",
"more_itertools",
"miniwdl @ git+https://github.com/chanzuckerberg/miniwdl.git",
"pytest-celery",
]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
    ]

[project.scripts]
ngs_pipeline = "app.app:main"
