@startuml
(*) --> "Clinicians provide biopsies (tumor samples) and order diagnostic panels"
--> "Pathologists or scientists forward assignments to laboratory"
--> "Laboratory extracts DNA/RNA from tumor samples and prepares NGS libraries for targeted sequencing"
--> "CLC Workbench workflow"

--> ===B1===
--> "Pan Cancer analysis (external)"
--> "liftover remap zu hg19"
--> "upload liftover files to MH Guide"
--> "MH Guide provides final medical reports"
--> ===B3===

===B1=== --> "Panel analysis (including Pan Cancer Analysis internal)"
--> ===B2===

===B1=== --> "CNV analysis"
--> ===B2===

===B1=== --> "RNA fusion analysis"
--> ===B2===

===B2=== --> "verify/check quality"
--> "sort and analyse excel files"
--> "interpretation of sequence variants and/or copy number variations and/or fusions"
--> "report sequence variants and/or copy number variations and/or fusions to the pathologists"
--> "pathologists finalize and approve medical reports"
--> ===B3===

--> "provide diagnosis back to the clinicians"
--> (*)
@enduml
