@startuml
left to right direction

actor "Doctor"
actor Patient

actor Pathologist
actor Bioinformatician

package "pathology workflow" {
  usecase "Develope ngs_pipeline" as develope
  usecase "provide tumor sample" as sample
  usecase "get targeted diagnosis" as diagnosis
  usecase "do biopsy peparation/analysis" as biopsy
  usecase "get treatment" as treatment
  usecase "get explanation/personal data" as explanation
  usecase "provide diagnosis"
  usecase "write diagnosis"

  usecase "provide documentation"

  package "ngs pipeline" {
    usecase "cnv analysis"
    usecase "liftover remap"
    usecase "monitor biopsy quality"
    usecase "provide logs"
  }

}

Bioinformatician --> (provide logs)
Bioinformatician --> (provide documentation)

Bioinformatician --> develope
Bioinformatician --> (cnv analysis)
Bioinformatician --> (liftover remap)
Bioinformatician --> (monitor biopsy quality)
Bioinformatician --> (write diagnosis)

Doctor --> sample
Doctor --> diagnosis

Pathologist --> biopsy
Pathologist --> (write diagnosis)

Patient --> explanation
Patient --> treatment
Patient --> diagnosis
@enduml
