@startuml
left to right direction

actor "Doctor"
actor Patient

actor Pathologist
actor Bioinformatician

package "pathology workflow" {
  usecase "Develope ngs_pipeline" as develope
  usecase "provide tumor sample" as sample
  usecase "get medical report" as diagnosis
  usecase "order molecular pathology diagnosis" as order
  usecase "tumor peparation/analysis" as biopsy
  usecase "get treatment" as treatment
  usecase "obtain medical discussion" as explanation
  usecase "write medical report"
  usecase "provide documentation"
  usecase "write previous findings"

  package "ngs pipeline" {
    usecase "DNA/RNA analysis" as panel
    usecase "CNV analysis"
    usecase "liftover remap"
    usecase "provide logs"
  }

}

Bioinformatician --> (provide logs)
Bioinformatician --> panel
Bioinformatician --> (CNV analysis)
Bioinformatician --> (provide documentation)
Bioinformatician --> develope
Bioinformatician --> (liftover remap)
Bioinformatician --> (write previous findings)

Doctor --> sample
Doctor --> order
Doctor --> diagnosis

Pathologist --> biopsy
Pathologist --> (write medical report)

Patient --> explanation
Patient --> treatment
Patient --> diagnosis
@enduml
